version: "3.8"
services:
  #===========================>> Api
  api:
    # build:
    #   context: ./api/.
    #   dockerfile: Dockerfile
    image: node-auth-service-api
    ports:
      - 8082:8082
    volumes: 
      - ./api/src:/usr/app/src
    networks:
      - node-auth_node-auth

  #===========================>> Engine
  engine:
    build:
      context: ./engine/.
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes: 
      - ./engine/src:/usr/app/src
    networks:
      - node-auth_node-auth
  #===========================>> SOCKET
  socket:
    build:
      context: ./socket/.
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes: 
      - ./socket/src:/usr/app/src
    networks:
      - node-auth_node-auth
  #===========================>> Cache
  cache:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data
    networks:
      - node-auth_node-auth
networks:
  node-auth_node-auth:
    external: true