# docker stack deploy --compose-file docker-ss-compose.yml node-auth-service
version: "3.8"
services:
  #===========================>> Socket
  socket:
    image: node-auth-service-socket
    ports:
      - 8083:8083
    environment:
      PORT: 8083
      REDIS_IP: cache
      REDIS_PORT: 6379
    volumes: 
      - ./socket/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 1
