# docker stack deploy --compose-file docker-ss-compose.yml socket
version: "3.8"
services:
  #===========================>> Socket
  socket:
    image: node-auth-service-socket
    ports:
      - 8083:8083
    volumes: 
      - ./socket/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 2
