version: "3.8"
services:
  #===========================>> Api
  api:
    build:
      context: ./api/.
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      PORT: 8082
    volumes: 
      - ./api/src:/usr/app/src

  #===========================>> Engine
  engine:
    build:
      context: ./engine/.
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      PORT: 8081
      REDIS_IP: cache
      REDIS_PORT: 6379
      API_IP: api
      API_PORT: 8082
    volumes: 
      - ./engine/src:/usr/app/src

  #===========================>> SOCKET
  socket:
    build:
      context: ./socket/.
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      PORT: 8083
      REDIS_IP: cache
      REDIS_PORT: 6379
    volumes: 
      - ./socket/src:/usr/app/src

  #===========================>> Cache
  cache:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data