version: "3.8"
services:

  #===========================>> Engine
  engine:
    image: node-auth-service-engine
    ports:
      - 8081:8081
    volumes: 
      - ./engine/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - engine
networks:
  # node_auth:
    # driver: overlay
    # external: true

  engine:
    # external: true