# docker stack deploy --compose-file docker-as-compose.yml node-auth-service
version: "3.8"
services:
  #===========================>> Api
  api:
    image: node-auth-service-api
    ports:
      - 8082:8082
    environment:
      PORT: 8082
    volumes: 
      - ./api/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 1