# docker stack deploy --compose-file docker-swarm-compose.yml node-auth-service
version: "3.8"
services:
  #===========================>> Api
  api:
    image: node-auth-service-api
    ports:
      - 8082:8082
    volumes: 
      - ./api/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 2

  #===========================>> Socket
  socket:
    image: node-auth-service-socket
    ports:
      - 8083:8083
    volumes: 
      - ./socket/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 2

  #===========================>> Engine
  engine:
    image: node-auth-service-engine
    ports:
      - 8081:8081
    volumes: 
      - ./engine/src:/usr/app/src
    deploy:
      mode: replicated
      replicas: 2

  #===========================>> Cache
  cache:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data
    deploy:
      mode: replicated
      replicas: 2