# docker stack deploy --compose-file docker-cs-compose.yml node-auth-service
version: "3.8"
services:

  #===========================>> Cache
  cache:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data
    deploy:
      mode: replicated
      replicas: 2